@startuml
'https://plantuml.com/component-diagram

package core {
    component Agent
    interface Resolver
    interface Handler

    Resolver )- Agent
    Agent -( Handler

    component route53
    Handler - route53
}
@enduml